In [10]:
import numpy as np

1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:

In [11]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

a. Calculate the sum, mean, median, and standard deviation of the elements in the array.

In [12]:
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"standard deviation: {np.std(arr)}")

Sum: 210
Mean: 10.5
Median: 10.5
standard deviation: 5.766281297335398


b. Find the indices of elements greater than 10 in the array.

In [32]:
indices = np.where(arr > 10)
print(indices)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16

a. Print the array.

In [14]:
arr_2d = np.arange(1,17).reshape(4,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

b. Find the transpose of the array.

In [15]:
print(f"Transpose of arr_2d:\n{np.transpose(arr_2d)}")

Transpose of arr_2d:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


c. Calculate the row-wise and column-wise sums of the array.

In [31]:
print(f"Row wise sum\n{np.sum(arr_2d, axis=1)}")
print(f"Column wise sum\n{np.sum(arr_2d, axis=0)}")

Row wise sum
[10 26 42 58]
Column wise sum
[28 32 36 40]


3. Create two 3 X 3 arrays filled with random integers between 1 and 20.

In [19]:
array1 = np.random.randint(1, 21, size=(3, 3))
array2 = np.random.randint(1, 21, size=(3, 3))

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)

Array 1:
 [[ 8 14  4]
 [17 18 20]
 [17  7 17]]

Array 2:
 [[16 14 16]
 [10 20 14]
 [16  1 13]]


a. Perform element-wise addition, subtraction, and multiplication.

In [27]:
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Addition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)

Addition:
 [[24 28 20]
 [27 38 34]
 [33  8 30]]

Subtraction:
 [[ -8   0 -12]
 [  7  -2   6]
 [  1   6   4]]

Multiplication:
 [[128 196  64]
 [170 360 280]
 [272   7 221]]


b. Compute the dot product of the two arrays.

In [28]:
dot_product = np.dot(array1, array2) 

print("Dot Product:\n", dot_product)

Dot Product:
 [[332 396 376]
 [772 618 784]
 [614 395 591]]


4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows
and last two columns.

In [30]:
arr_1d = np.arange(1, 13)
arr_reshaped = arr_1d.reshape(3, 4)
print("Reshaped Array:\n", arr_reshaped)

sliced_arr = arr_reshaped[:2, -2:]
print("\nSliced Array:\n", sliced_arr)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array:
 [[3 4]
 [7 8]]
