# Module 10: Advanced Python Tools - Assignment 1
## Working with NumPy

**Objective:** Understand the basics of NumPy, array creation, and manipulation.

In [1]:
import numpy as np

### Task 1: 1D Array Operations
We create a 1D NumPy array containing integers from 1 to 20. Then we compute descriptive statistics (sum, mean, median, standard deviation) and extract indices where elements exceed 10.


In [2]:
# Create a 1D array from 1 to 20
arr_1d = np.arange(1, 21)
print("Original 1D Array:", arr_1d)

# 1.a Calculate statistics
arr_sum = np.sum(arr_1d)
arr_mean = np.mean(arr_1d)
arr_median = np.median(arr_1d)
arr_std = np.std(arr_1d)

print(f"Sum: {arr_sum}")
print(f"Mean: {arr_mean}")
print(f"Median: {arr_median}")
print(f"Standard Deviation: {arr_std:.4f}")

# 1.b Find indices of elements greater than 10
indices_gt_10 = np.where(arr_1d > 10)[0]
print("Indices of elements > 10:", indices_gt_10)


Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.7663
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]


### Task 2: 2D Array Matrix Operations
We construct a $4 \times 4$ matrix ranging from 1 to 16, compute its transpose, and calculate row-wise and column-wise aggregations.


In [3]:
# Create a 4x4 2D array
arr_2d = np.arange(1, 17).reshape(4, 4)
print("Original 2D Array:\n", arr_2d)

# 2.b Transpose of the array
arr_transpose = arr_2d.T
print("\nTransposed Array:\n", arr_transpose)

# 2.c Row-wise and column-wise sums
row_sums = np.sum(arr_2d, axis=1)
col_sums = np.sum(arr_2d, axis=0)

print("\nRow-wise sums:", row_sums)
print("Column-wise sums:", col_sums)


Original 2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transposed Array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]


### Task 3: Operations on Random Arrays
We generate two distinct $3 \times 3$ matrices populated with random integers between 1 and 20. We perform element-wise addition, subtraction, multiplication, and matrix dot product multiplication.


In [4]:
# Set seed for reproducibility
np.random.seed(42)

# Create two 3x3 random arrays between 1 and 20
matrix_A = np.random.randint(1, 21, size=(3, 3))
matrix_B = np.random.randint(1, 21, size=(3, 3))

print("Matrix A:\n", matrix_A)
print("\nMatrix B:\n", matrix_B)

# 3.a Element-wise operations
print("\nElement-wise Addition:\n", matrix_A + matrix_B)
print("\nElement-wise Subtraction:\n", matrix_A - matrix_B)
print("\nElement-wise Multiplication:\n", matrix_A * matrix_B)

# 3.b Dot product
dot_product = np.dot(matrix_A, matrix_B)
print("\nDot Product Matrix multiplication:\n", dot_product)


Matrix A:
 [[ 7 20 15]
 [11  8  7]
 [19 11 11]]

Matrix B:
 [[ 4  8  3]
 [ 2 12  6]
 [ 2  1 12]]

Element-wise Addition:
 [[11 28 18]
 [13 20 13]
 [21 12 23]]

Element-wise Subtraction:
 [[ 3 12 12]
 [ 9 -4  1]
 [17 10 -1]]

Element-wise Multiplication:
 [[ 28 160  45]
 [ 22  96  42]
 [ 38  11 132]]

Dot Product Matrix multiplication:
 [[ 98 311 321]
 [ 74 191 165]
 [120 295 255]]


### Task 4: Reshaping and Slicing
We initialize a 1D array of 12 elements, reconstruct it into a $3 \times 4$ grid shape, and filter specific rows and columns using multi-axis slicing syntax.


In [5]:
# Create 1D array of size 12 and reshape to 3x4
base_arr = np.arange(1, 13)
reshaped_arr = base_arr.reshape(3, 4)
print("Reshaped 3x4 Array:\n", reshaped_arr)

# Slice the first two rows and last two columns
# Rows: 0, 1 (up to index 2 exclusive)
# Columns: last two (-2 to end)
sliced_arr = reshaped_arr[0:2, -2:]
print("\nSliced Sub-array (First 2 rows, Last 2 columns):\n", sliced_arr)


Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Sub-array (First 2 rows, Last 2 columns):
 [[3 4]
 [7 8]]
